output_dir: ./results/ampc_feature_analysis

datasets:
  - name: AMPC_Feature_Aligned
    reference: /Users/sanazkazeminia/Documents/mol_test_suite/data/project_data/data/AMPC_beta_lactamase/FEATURE_MAP_ALIGNED
    methods: {}

analyses:
  - feature_rewards

feature_rewards:
  hotspot_pkl: /Users/sanazkazeminia/Documents/analysis_suite/data/run_data/ampc_hotspot_global_centered_eps0.5_min10_aromatic5.pkl

plotting:
  figure_format: [png, svg]
  dpi: 300

